### ISSUE TITLE
[epic] Support uploading new resources via JWT Authorization -> Giftless -> Cloud Storage flow 

### ISSUE THREAD

**Issue by shevron** [datopian/ckanext-external-storage#1]
Override CKAN's default resource uploading flow with a client-side driven flow:

```
     ┌───────┐          ┌────────┐                               ┌────────┐          ┌────────────┐          ┌────┐
     │Browser│          │AuthzAPI│                               │Giftless│          │CloudStorage│          │CKAN│
     └───┬───┘          └───┬────┘                               └───┬────┘          └─────┬──────┘          └─┬──┘
         │    authorize     │                                        │                     │                   │   
         │─────────────────>│                                        │                     │                   │   
         │                  │                                        │                     │                   │   
         │      token       │                                        │                     │                   │   
         │<─────────────────│                                        │                     │                   │   
         │                  │                                        │                     │                   │   
         │authorize_upload  │                                        │                     │                   │   
         │(token, supported adapters, resource sha256, resource size)│                     │                   │   
         │───────────────────────────────────────────────────────────>                     │                   │   
         │                  │                                        │                     │                   │   
         │             upload action                                 │                     │                   │   
         │             (transfer adapter, href, headers)             │                     │                   │   
         │<───────────────────────────────────────────────────────────                     │                   │   
         │                  │                                        │                     │                   │   
         │                  │         PUT (href, headers, file)      │                     │                   │   
         │─────────────────────────────────────────────────────────────────────────────────>                   │   
         │                  │                                        │                     │                   │   
         │                  │              OK (file meta)            │                     │                   │   
         │<─────────────────────────────────────────────────────────────────────────────────                   │   
         │                  │                                        │                     │                   │   
         │                  │            add resource (resource meta, file meta)           │                   │   
         │─────────────────────────────────────────────────────────────────────────────────────────────────────>   
         │                  │                                        │                     │                   │   
         │                  │                              OK        │                     │                   │   
         │<─────────────────────────────────────────────────────────────────────────────────────────────────────   
     ┌───┴───┐          ┌───┴────┐                               ┌───┴────┐          ┌─────┴──────┐          ┌─┴──┐
     │Browser│          │AuthzAPI│                               │Giftless│          │CloudStorage│          │CKAN│
     └───────┘          └────────┘                               └────────┘          └────────────┘          └────┘
```

Most of the client-side logic for this is implemented in the ckan3-js-dsk work done here: https://gitlab.com/datopian/experiments/ckan3-js-sdk

### Acceptance Criteria

* [ ] When a new resource is added to a Dataset and the button Save is clicked the resource should be uploaded to the specific Blob and the page should redirect to the dataset's view.

* [ ] When a new resource is added to a Dataset and the button Save & Add Another is clicked the resource should be uploaded to the specific Blob and the page should be redirected to the resource_new form so the user can add another resource

* [ ] The name of the uploaded resource should be: filename? url?

### Tasks

* [x] Create a new javascript ckan module and override the upload actions to call the SDK instead of the CKAN logic.

* [x] The following templates should be overriden to add the new logic:

  * [x] resource_edit.hmtl

  * [x] new_resource.html

  * [x] new_resource_not_draft.html

### Analysis

Open Questions:

* [x] Where are we going to call the SDK? (I guess when clicking on Save or Save Another)

* [ ] Which parameters it will receive? (I guess a complete Dataset object with the new resource/list of resources?)

* [ ] Which parameters it will return? (If we call ckan create api from the SDK then probably it will just redirect to the dataset page)

* [ ] What are we going to store in CKAN Metastore? (Link to the dataset? Hash? Filename?)

**Comment by shevron** [comment]
This is now fully implemented and merged.
